### ISSUE TITLE
Archive query doesn't work as expected

### ISSUE THREAD

**Issue by royceschultz** [TheBuffsOfWallStreet/Sponsor#13]
https://github.com/TheBuffsOfWallStreet/Sponsor/blob/8cf66948b9e50d1956f98fb103644879397c5534/ArchiveScraping/Archive.py#L58

As is, it includes non-bloomberg shows. We also want to be able to filter for other shows like Fox News or CNN.

**Comment by chacetrev10** [comment]
On this website ( https://archive.org/advancedsearch.php)  you can submit an advanced search. Inspect the webpage, go to the network tab and after submitting the request, you will see something like search.php?query=' query '. Set q in the payload equal to 'query'.
